@startuml Busca HQs
title Vitrine de HQ
FrontEnd -> BackEnd : Requisitar informação de Hqs paginados
FrontEnd --> BackEnd : Informação das hqs
Minio --> FrontEnd : Imagem de HQ
FrontEnd -> Minio : Buscar imagens
@enduml